# Importing necessary Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load the dataset

In [2]:
df = pd.read_csv("E:/Downloads/Churn dataset.zip")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.isnull().sum()                       # Check for missing values

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.duplicated().sum()                # Check for duplicated rows

np.int64(0)

In [8]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

# Dropping Unnecessary columns

In [9]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

# Encode categorical variables

In [11]:
df = pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)

In [12]:
df = df.astype(int)

In [13]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,1,0,0,0
1,608,41,1,83807,1,0,1,112542,0,0,1,0
2,502,42,8,159660,3,1,0,113931,1,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0,0
4,850,43,2,125510,1,1,1,79084,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,0,1
9997,709,36,7,0,1,0,1,42085,1,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0,0

In [14]:
# Splitting the features and target
X = df.drop("Exited",axis=1)
y = df["Exited"]

# Performing Train-Test Split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [16]:
# Scaling the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]], shape=(8000, 11))

In [18]:
X_train.shape

(8000, 11)

In [19]:
X_test

array([[-1.03768121,  0.77498705, -1.0482813 , ..., -0.58312392,
        -0.57273139,  0.91509065],
       [ 0.30708683, -0.46686456, -0.70174202, ..., -0.58312392,
        -0.57273139,  0.91509065],
       [-1.23422423,  0.29735181, -1.0482813 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       ...,
       [-0.86182692, -0.46686456,  1.72403288, ..., -0.58312392,
         1.74601919,  0.91509065],
       [-0.30323097, -0.84897275, -1.0482813 , ...,  1.71490137,
        -0.57273139, -1.09278791],
       [ 0.04847759,  1.25262228,  1.3774936 , ...,  1.71490137,
        -0.57273139,  0.91509065]], shape=(2000, 11))

In [20]:
X_test.shape

(2000, 11)

# Model Training

In [21]:
import tensorflow

C:\Users\User\Parth\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [22]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(11,activation="relu",input_dim=11))
model.add(Dense(11,activation="relu"))
model.add(Dense(1,activation="sigmoid"))      # Output will be sigmoid only

C:\Users\User\Parth\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

# target feature --> binary
# loss="binary_crossentropy"

In [25]:
model.compile(loss="binary_crossentropy", optimizer="Adam")

In [26]:
model.fit(X_train,y_train,epochs=200)

Epoch 1/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.5216
Epoch 2/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4344
Epoch 3/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4058
Epoch 4/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3873
Epoch 5/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3749
Epoch 6/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3664
Epoch 7/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3601
Epoch 8/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3557
Epoch 9/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3514
Epoch 10/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3490
Epoch 11/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3467
Epoch 12/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3447
Epoch 13/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3436
Epoch 14/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3421
Epoch 15/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3409
Epoch 16/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3406
Epoch 17/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3388
Epoch 18/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3383
Epoch 19/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3373
Epoch 20/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3369
Epoch 21/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3356
Epoch 22/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3348
Epoch 23/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3341
Epoch 24/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3340
Epoch 25/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3326
Epoch 26/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3323
Epoch 27/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3318
Epoch 28/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3311
Epoch 29/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3307
Epoch 30/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3300
Epoch 31/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3297
Epoch 32/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3295
Epoch 33/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3286
Epoch 34/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3285
Epoch 35/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3281
Epoch 36/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3280
Epoch 37/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3278
Epoch 38/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3271
Epoch 39/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3270
Epoch 40/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3265
Epoch 41/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3264
Epoch 42/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3264
Epoch 43/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3260
Epoch 44/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3260
Epoch 45/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3256
Epoch 46/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3254
Epoch 47/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3254
Epoch 48/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3254
Epoch 49/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3252
Epoch 50/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3250
Epoch 51/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3251
Epoch 52/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3243
Epoch 53/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3246
Epoch 54/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3247
Epoch 55/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3245
Epoch 56/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3241
Epoch 57/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3237
Epoch 58/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3238
Epoch 59/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3233
Epoch 60/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3238
Epoch 61/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3236
Epoch 62/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3240
Epoch 63/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3228
Epoch 64/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3236
Epoch 65/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3231
Epoch 66/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3228
Epoch 67/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3227
Epoch 68/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3226
Epoch 69/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3230
Epoch 70/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3228
Epoch 71/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3225
Epoch 72/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3225
Epoch 73/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3224
Epoch 74/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3220
Epoch 75/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3224
Epoch 76/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3217
Epoch 77/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3221
Epoch 78/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3223
Epoch 79/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3219
Epoch 80/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3215
Epoch 81/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3213
Epoch 82/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3216
Epoch 83/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3212
Epoch 84/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3216
Epoch 85/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3220
Epoch 86/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3213
Epoch 87/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3215
Epoch 88/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3212
Epoch 89/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3213
Epoch 90/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3213
Epoch 91/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3210
Epoch 92/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3209
Epoch 93/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3210
Epoch 94/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3206
Epoch 95/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3207
Epoch 96/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3202
Epoch 97/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3197
Epoch 98/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3205
Epoch 99/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3203
Epoch 100/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3202
Epoch 101/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3200
Epoch 102/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3200
Epoch 103/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3199
Epoch 104/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3199
Epoch 105/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3193
Epoch 106/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3204
Epoch 107/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3195
Epoch 108/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3195
Epoch 109/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3194
Epoch 110/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3195
Epoch 111/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3193
Epoch 112/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3195
Epoch 113/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3193
Epoch 114/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3190
Epoch 115/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3190
Epoch 116/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3195
Epoch 117/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3192
Epoch 118/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3186
Epoch 119/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3188
Epoch 120/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3191
Epoch 121/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3188
Epoch 122/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3191
Epoch 123/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3183
Epoch 124/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3186
Epoch 125/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3184
Epoch 126/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3184
Epoch 127/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3183
Epoch 128/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3190
Epoch 129/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3187
Epoch 130/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.3185
Epoch 131/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3183
Epoch 132/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3180
Epoch 133/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3176
Epoch 134/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3180
Epoch 135/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3181
Epoch 136/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3178
Epoch 137/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3183
Epoch 138/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3184
Epoch 139/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3177
Epoch 140/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.3182
Epoch 141/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3177
Epoch 142/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3177
Epoch 143/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3170
Epoch 144/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3178
Epoch 145/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3178
Epoch 146/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.3177
Epoch 147/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3177
Epoch 148/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3174
Epoch 149/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3176
Epoch 150/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3176
Epoch 151/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3176
Epoch 152/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3177
Epoch 153/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3173
Epoch 154/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3178
Epoch 155/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3176
Epoch 156/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3173
Epoch 157/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3177
Epoch 158/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3171
Epoch 159/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3169
Epoch 160/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3171
Epoch 161/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3177
Epoch 162/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3170
Epoch 163/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3171
Epoch 164/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3173
Epoch 165/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3172
Epoch 166/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3167
Epoch 167/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3173
Epoch 168/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3165
Epoch 169/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3165
Epoch 170/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3168
Epoch 171/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3163
Epoch 172/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3170
Epoch 173/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3169
Epoch 174/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3165
Epoch 175/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3165
Epoch 176/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.3167
Epoch 177/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3168
Epoch 178/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3163
Epoch 179/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3162
Epoch 180/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3162
Epoch 181/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3163
Epoch 182/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3169
Epoch 183/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3156
Epoch 184/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3166
Epoch 185/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3163
Epoch 186/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3158
Epoch 187/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3161
Epoch 188/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3158
Epoch 189/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3156
Epoch 190/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.3160
Epoch 191/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.3157
Epoch 192/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.3159
Epoch 193/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.3154
Epoch 194/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 0.3160
Epoch 195/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3153
Epoch 196/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.3157
Epoch 197/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.3154
Epoch 198/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 0.3154
Epoch 199/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3157
Epoch 200/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3156

In [27]:
model.layers[0].get_weights()          # Weights and bias

[array([[ 1.85706019e-02, -7.89695010e-02, -3.42618977e-03,
         -1.37022600e-01, -1.75345853e-01, -2.10949138e-01,
         -1.49196938e-01, -1.25242144e-01,  9.86729935e-02,
         -7.61286914e-02,  2.49763262e-02],
        [-6.34970486e-01,  4.38422292e-01, -6.67711258e-01,
          2.90813893e-01, -9.45252538e-01, -7.79250264e-02,
          1.05105944e-01,  8.65018904e-01, -1.39696681e+00,
          4.50032115e-01, -8.05112481e-01],
        [ 8.80934671e-03,  2.53376216e-02,  1.92530245e-01,
         -5.78929782e-01,  1.13150477e-01,  5.14127314e-01,
         -1.80202886e-01,  9.65713114e-02,  4.71349388e-01,
          1.72280171e-03,  1.49935856e-01],
        [-1.02634752e+00, -3.01662087e-01,  2.37776488e-01,
          8.23618710e-01, -9.66798246e-01,  9.83714819e-01,
          6.39259040e-01, -1.74198106e-01,  2.70958006e-01,
         -3.54169220e-01,  4.32352945e-02],
        [-7.38380030e-02, -1.13646424e+00,  2.25473672e-01,
          5.24646742e-03,  1.43482670e-01, -6.35059923e-02,
          1.10023367e+00,  1.39980459e+00, -4.18601096e-01,
         -4.72351640e-01,  8.24840888e-02],
        [-5.38308732e-02,  1.42701358e-01,  4.36007231e-01,
         -1.70418024e-01,  2.11828984e-02,  1.80229828e-01,
         -3.12944502e-02,  1.76701322e-01,  2.83421457e-01,
         -1.44971721e-02,  2.54712701e-01],
        [-1.29414156e-01, -3.65796745e-01, -2.62282372e-01,
         -3.37661564e-01, -2.34295830e-01,  5.17023861e-01,
         -3.83126587e-01,  2.65478879e-01, -1.05036953e-02,
          7.67406702e-01, -3.22145015e-01],
        [-1.50150910e-01,  7.15996251e-02,  2.48328492e-01,
          9.93190408e-02, -1.90010265e-01,  2.19925269e-02,
          9.48302224e-02,  1.29543478e-02, -5.61385823e-04,
          1.26094207e-01,  2.74479669e-02],
        [-6.98886693e-01,  2.95770079e-01,  2.89245158e-01,
          1.92328151e-02,  2.35946506e-01,  2.81822294e-01,
         -1.71561182e-01,  3.55321541e-02, -2.69790053e-01,
         -1.30051017e-01, -9.53506529e-02],
        [ 2.78522462e-01, -1.18479192e-01, -2.58311212e-01,
         -4.72163528e-01, -5.92110276e-01, -1.92602705e-02,
          1.52453054e-02, -6.24824055e-02, -9.22436342e-02,
         -2.38570087e-02, -1.03570245e-01],
        [-1.12943724e-01, -1.14661016e-01, -8.10767829e-01,
          4.91998523e-01, -3.49036247e-01, -4.80612099e-01,
          4.09363024e-02, -4.03229445e-02,  3.51001292e-01,
          4.11112577e-01,  1.16496611e+00]], dtype=float32),
 array([ 1.3185308 ,  0.28915623,  0.73293746,  0.28609365,  0.12084153,
         0.37887704,  0.09786893, -0.00617093,  0.2877463 ,  0.1624105 ,
         0.21050976], dtype=float32)]

In [28]:
y_log = model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

In [29]:
y_pred = np.where(y_log > 0.5,1,0)

In [30]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], shape=(2000, 1))

In [31]:
accuracy = accuracy_score(y_test,y_pred)

In [32]:
accuracy

0.864